#!/bin/sh
# autopkgtest check: Build and run a program against visp, to verify that the
# headers and pkg-config file are installed correctly
# (C) 2013 Thomas Moulard
# Author: Thomas Moulard <thomas.moulard@gmail.com>

set -e

WORKDIR=$(mktemp -d)
trap "rm -rf $WORKDIR" 0 INT QUIT ABRT PIPE TERM
cd $WORKDIR
cat <<EOF > visptest.cpp
#include <visp/vpColor.h>

int main()
{
    vpColor red = vpColor::red;
    return 0;
}
EOF

g++ -o visptest visptest.cpp `pkg-config --cflags --libs visp`
echo "build: OK"
[ -x visptest ]
# often prints "libdc1394 error: Failed to initialize libdc1394" to stderr,
# avoid test failure due to that
./visptest 2>&1
echo "run: OK"
