#!/bin/sh
# autopkgtest check: Build and run a program against visp, to verify that the
# headers and pkg-config file are installed correctly
# (C) 2013 Thomas Moulard
# Author: Thomas Moulard <thomas.moulard@gmail.com>

set -e

WORKDIR=$(mktemp -d)
trap "rm -rf $WORKDIR" 0 INT QUIT ABRT PIPE TERM
cd $WORKDIR
cat <<EOF > glibtest.cpp
#include <visp/vpColor.h>

int main()
{
    vpColor red = vpColor::red;
    return 0;
}
EOF

gcc -o visptest visptest.cpp `pkg-config --cflags --libs visp`
echo "build: OK"
[ -x visptest ]
./visptest
echo "run: OK"
