#!/bin/sh

set -e

ARCH=`dpkg-architecture -qDEB_BUILD_ARCH`
V=2

PKGS="libvisp"

for pkg in ${PKGS}; do
    f=`echo ${pkg} | sed 's|-|_|g'`
    pkgkde-gensymbols -p${pkg}${V} -v${V} -Osymbols-${pkg}.${ARCH} \
	-edebian/${pkg}${V}/usr/lib/*/${f}.so.${V}
    pkgkde-symbolshelper create -o debian/${pkg}${V}.symbols -v ${V} \
	symbols-${pkg}.${ARCH}
done
